"""Compiled pixel portrait: palette indices on a 96 px grid.

Generated by `scripts/gen-sprite.py` from the portrait named in profile.toml;
do not edit by hand.
"""

SIZE = 96

PALETTE = (
    "#fff7ef",  # milk
    "#f7e8d8",  # cream
    "#d9c2ad",  # latte
    "#b39a89",  # taupe
    "#8a6a55",  # cocoa
    "#4a3427",  # ink
    "#dba85f",  # amber
    "#f0cf8f",  # honey
    "#dd8f8c",  # rose
    "#ffffff",  # white
    "#a48e91",  # portrait0
    "#ec9c5e",  # portrait1
    "#26211f",  # portrait2
    "#784025",  # portrait3
    "#f8dd75",  # portrait4
    "#ecba77",  # portrait5
)

ROWS = (
    ".........................................aaaaaaaaaaaaaa.........................................",
    "....................................aaaaaaaaaa4aaaaaaaaaaaaa....................................",
    ".................................83aaaaaaaaaaaaaaaaaaaaaaaaaaaa.................................",
    "..............................aaa883aaaaaa4aaaaaaaaaaaaaaaaaaaaaaa..............................",
    "............................aaaaa883aaaaaa4aaaaaaaaaaaaaaaaaaaaaaaaa............................",
    "..........................4aaaaaa33aaaa3aa44aaaaaaaaaaaaaaaaaaaaaaaaaa..........................",
    "........................4aaaaaaaaaaa8f8baa4aaaaaaaaaaaaaaaaaaaaaaaaaaaaa........................",
    "......................aaaaaaaaaaaaaa3883aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa......................",
    ".....................a3333aaaaaaaaa333aaaaaaaaaaaaaaaaaaaaa3aaaaaaaaaaaaaaa.....................",
    "...................a33663333aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaad...................",
    "..................a3b8836633aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa3aaaaa45..................",
    ".................3a368333833aaaaaaaaaaaaaaaaaaaaaaaaaaa63aaaaaaaaaaaa32aaaa3455.................",
    "................b633333aa33aaaaaaaaaaaaaaaaaaaaaaaaaaa3b3aaa63aaaaaaa3a336f6d54d................",
    "...............bb633aaaaaaaaaaaaaaaaaaaaaaaaaa363aaaaa663aaa6aaaaaaa2a6b686444554...............",
    "..............bbb63aaaaaaaaaaaaaaaaaaaaaaaaaaaa3a333aa3aaaaa3aaaaaaaa36b33364d5544..............",
    ".............6bbbb83aaa33aaaaaaaaaaaaaaaaaaaaaaaa333333aaaaa3aaaaaaa3f663a34d5dc5dd.............",
    "............eebbbbb8333383aaaaaaaaaaaaaaaaaaaaaa3333aaaaaaaaaaaaaaaa3b63a3345c4dcc5c............",
    "...........eeebbbbbb83388833aaaaaaaaaaaaaaaaaaaaa3aaaaaaaaaaaaaa77f383aa34d5c54455ccc...........",
    "..........ee6eeebbbbb66b8883aaaaaaaaaaaaaaaaaa3333aaaaaaaaaaaaa27f633aaa3644d344d55ccc..........",
    ".........666bbeebbbbb8883383aaaaaaaaa33a3aaaa336833aaaaaaaaaaaaa2e63aaaaaaaaa344d5ccccc.........",
    ".........aaabb66ebbbbbb63a333aaaaaa333888aaaa3bb833aaaaaaaaaaaaa27f6aaaaaaa3384d5cccccc.........",
    "........a33a8bbbbbbbbbbb3aaa8888883333888aaaa38333aaaaaaaaaaaaaaa333aaaaaa364d5dcccccccc........",
    ".......aa33a3bbbfbbbbbb8aaaa88888883883883aa33aaaaaaaaa33aaaaa33aaaaaaaaaa64d5c5cccccccc10.......",
    ".......aa8838bbbffbbbb8aaaaa88f88838883883a333aaaaaaaa383aaaa3a3aaaaaaaaa364d55cccccccccc.......",
    "......aa8b8888bffff8388aaaaa888883338338333333aa3aaaaa3333aaf3aaaaaa33333386d5cccccccccccc......",
    "......aa8b88aa8fff63a33aaaa888888833888888888838b33aa33333aa63aaa33333333364d5cccccccccccc......",
    ".....aaaa8f6aa3ffff66883aaa888888888888888bbb8bbbbb838833aa363a33366683366664dccccccccccccc.....",
    ".....a33a8ff3a8ffffeff68aaa3888888888888bbbbbbbbbbbbb8883a3f663366bb66866bb6dd5cccccccccccc.....",
    "....aa388fff338883fef6f3aaa88bbbbb888bbbbbbbbbbbbbbbb8883affbb8bbbbb666bbbb4d5cccc5ccccccccc....",
    "....aa8fff8f8a8383fff83aaaa88bbbbbbbbbbbbbbbbbbbbbbbb88833ff86bbbbbbbbbbbbbd5c5cc5cc5ccccccc....",
    "...aaa8888883388ff8f83aaaaa8bbbbbbbbbbbbbbbbb6ebbbbb8888338f86bbbbbbbbbbbbdd555c55c5ccccccccc...",
    "...aa8888aaaaa8fffff883aaa3fbbbbbbbbbbbbbbbbeeebbbbbbbb8338b6bbbbbbbbbbbb4d5c5ddd5ccccccccccc...",
    "...a388f8aaaaa3f666bb663a38bbbbbbbbbbbbbbbbfeffbbbbbbbb8338bbbbbbe6bbbbbbd5c55dddd5cccccccccc...",
    "..a38fff3aaaa338fbbbbbb838ffbbbbfeefbbffffffff88bbbbbbbb886bbbbb6ebbbbbb4d5555dddd5ccccccccccc..",
    "..338fff8aa3f836fbbbbbf33ff8bbbb6eefeffbfffff8888bbbbbbbbbbb6eef66bbbb66d5c555dddd55ccc5cccccc..",
    "..488fe7f838f63bbbb6ef6a3886bbbbeefffef8bfff8888bbbbbbbbbbbb6ff3fe6eff24dcc555dddddccccccccccc..",
    ".dd8ffffffffbbbbbb6eef3a38fbbbbbeef888bfffbbbb88bbbbbbbbbbb6f2222fef22ad5c555dddcdd5c5cc5ccccc10.",
    ".5d4f2882f33bbbb6eeeef3a86bbbbbeeef88888fbbbbbbbbbbbf8bbbbb22222222222ddc555ddd5cdd45ccccc55ccc.",
    ".5dd3aaaa3a3bbbb6eee73a3eebbbb6ee7f8f888bbbbbbbbbbff2888bbf22222222224d55555ddd5c54dd5ccccccccc.",
    ".5d4daaf8386bbbbbeef2aa6eefbbeeeefff88ffbbbbbbff2227888888f7222222ff3dd55555dddd555c55ccccccc5c.",
    ".55dda3ffffbbeb6eee2aa6bb66eeeeef77ffffebbbbbf2222ff688888bf22222ffbdddd5555dddddd55c5ccccc5ccc.",
    "cc5d4422ffffeeeeeef336bbbbeeeee77ffffeeeeeefb2227e6bbbb888bf2222fbb6dd684dddddddddd555cccccccccc",
    "ccc5dd3a38feeeeeef88ffffbeeeeeefffffffeeeeeef2227efbbbbb88bf22226bbbbb8884ddddddddd4d5cccccc5ccc",
    "ccc55d4aa8feeeee7338fffefeeeee7f2222f7e7777222227ffffbbb88bbbf2fffbbbb888f6ddddddd44dd555cc5cccc",
    "5ccc5dd33fffeeef728ffffeeeee777722227772222222222ffffbbbbbbbbf7bbbbbbb66ffb6dddddddddd5cc5cccccc",
    "5ccc55d4eeeffff733ffeeffeee77772222277722222222227fffbbbbbbbbfbbbbbbbbbbfbbe64ddddd55dd5ccc5cccc",
    "55ccc5d6ffeee723a37eeffeee77772222222222222222777fffbbbbbbbbbffbbbbbbbbbfbfeef4dddddddd5cccccccc",
    "55ccc554ffe7222222222feee777f7222222222277727fbbbbbbbbbbbbbb6ef8bbbbbbbbfbfee774ddd4dd55c5ccccc5",
    "555ccc5df2222a222222227e7727fe222222222feef7fbbbbbbbbbbbbbb66ef8bbf6bbbbbbfe72224dd4dd555cc55555",
    "555ccc5d42222222222222772277e7222222277fe6bbbbbbbbbbbbbbbbfffffbbffbbbbbbff7721174dd4dd555c55d5c",
    "5555cccddf222222222222222777772222227fffbbbbbbbbbbbbbbbbbb8ffffbbffbbbbbbf721117e74ddddd555c5555",
    "5555ccc5d62222222222222222772222277ffbbbbbbbbbbbbbbbbbbbbb88ffbbbfbbbbbbf777117eeff4dddd555cdd55",
    "55555c55ddf22222222222222222222277fbbbbbbb6bbbbbbbbbbbbbbbbbbbbbbfbbbbbbf777777effff6ddd5555dd55",
    "55555cc55d42222222222222222222227ffbbbbbbbb6bbbfbbbbbbbbbbbbbbbfbbbbbb6ff77777eeb66fe6ddd555dd55",
    "455555c55dd2222222222222222222277fbbbbbbbbbbbbbbbbbbbbbbbbbbbbffbbbbbbef777777e66bbbe6ddddddd555",
    ".455555555d477227722222222222227fbbbbbbbb6bbbbbbbbbbbbbbbbbbbfbbbbbbbef777717ef6bbbbf664dddd555.",
    ".455555c55dd6fffff222222222777ffbbbbbbbbbbbb6ebbbfbbbbbbbbbbbbbbbbbbe77777777f6bbbbbbfe4dddddd5.",
    ".545555cc55d4ffffff7ff7777777fffbbbbbbbbbbbbeeeffbbbbbbbbbbbbbbbbbbbe777777f66bbbbbb6ee6664dddd.",
    ".5455555c55ddfeeeefffff77777ffebbbbeebbbbb6eeeeffbbbbbbbbbbbbbbbbbbf777777ebbbbbbbbe6eeeeef4ddd.",
    ".554555d5555d6eeeeeefffffeefffe6bbeee6bb6eeeeefffbbbbbbbebbbbbbbbee777777e66bbbb66e66eeeeee64dd.",
    "..555555d555ddeeeeeeeef666ee6beeeeeeeeeeeebbbfffbbbbbbb6ebbbbbbbee77efeeeeebbbbeee66eeeeeeee6d..",
    "..555555d555dd6eeeef664dd6feeeeeeeeeeeeee666eeebbbbbbbbbbbbbbbbfefeffeefeeebbbeeeeeeeee6eeebdd..",
    "..5555555d555ddfff64ddddd6eeeeeeeeeeeeeeeeeeeeebbbbfffbbbbb666bffff6eeee66bbbeeeeeeeee6eeebddd..",
    "...5c5555d5555d44dddddddddffeeeeeeeeeeeeeeeeeeefbbeefffbbbeeef6ff66efee6bbb6eeeeeeeeeeee6bddd...",
    "...cc55555d5555dddddddddddffffeeeeeeeeeeeeeeeeeeee77ffefeeeeeffffeeeee66bbeeeeeeeeeeeee6ddddd...",
    "...5555555dd555d4ddddddddd67ffeeeeeeeeeee7eeeeee777ffeee777ebbfe66f6e666eeeeeeef66eeeebdd44dd...",
    "....555555dd5555d4dddddddd477eeeeeeeeee77eeee777777ee77feeefbbe6d6666e46eeeeeee4446eebd44ddd....",
    "....5445555dd5555ddddd4ddd4f7eeeeeeeeee777777777777777fbffebbee66646e666666ee66444464ddddddd....",
    ".....444555d4d555dd4dddd4d4677eeeeeeee77777777777777ebbbfebbff6e66d6e66d466e64d44d4ddddddd5.....",
    ".....5445c55d45555d44dddddd677eeeeeee77777777777777e6bbbfbbfe6664646e6664666d4ddd46ddddddd5.....",
    "......4455c5d4d555d4ddddddd46eeeeeee77777777777777efbbbbbbfeeeee66666e646666d4ddd4dddddddd......",
    "......4445c55d4555dddddddddd47ee77777777777777777eef6bbfbfeee6eeee66466666666bd4dddddddddd......",
    ".......444555d4d555dddddddddd6777777777777777777eeebbb6eeeeeeee6e66dd466e66666bdddddddddd.......",
    ".......4445555d4555dddddddddd4f77777777777eeeeeeeebbbbeeeee666d4bddddddb6e6666ddddddddddd.......",
    "........444555d44555dddddddddd67777777777eeeeeeeeebbeb6eeeebb4dddddddddd464d44ddddddd55d........",
    ".........445555445555ddddddddd4f7e7777eeeeeeeeeeee6eeb6e6eebb66ddddddddddddddddddd5dddd.........",
    ".........444555d4455cdddddddddd47eeee7eeeeeeeeeeeeeee6e66ee66664dddddd4ddddddd5ddd55555.........",
    "..........445555d45555dddddddddd6eeeeeeeeeeeeeeeeeeeeeeeeee6664bddddddddddddd55ddd5d55..........",
    "...........44555d4455cdddddddddd4eeeeeeeeeeee66eeeeeeeeeee666bd6bddddddd55ddd55d4d555...........",
    "............4555544dcc5ddddddddd46eeeeeee6beeee664b66eeeee664ddbddddd555555ddd55d555............",
    ".............45555445cc5ddddddddd4eeeeeeeeee6664dd466eeeee666ddddbddd55555555555555.............",
    "..............5555d45cc5dddddddddd66eeeeeee66644ddd6eee6fe6b64ddd6dd55555555555555..............",
    "...............5555d45cc5ddddddddd4feffeeee666d4d4dd666666666bdddddddd55555c555cc...............",
    "................555d44cc5ddddd555dd66bbeee6f6644dddd4d46b66e64ddddddd55555c555cc................",
    ".................555d4555dddd555ddd46eeee66664dddddd6dddddbee4ddddddd5555555ccc.................",
    "..................55d44555d555d44ddd6eeef6bdddddd44ddddddddb6ddd55555555cccccc..................",
    "...................55d45555ccd4ddddd4fee66bddd4ddddddddddddddddd555555555c5cc...................",
    ".....................ddd55ccc4d5dddd46eee66bdd4dddddddddddddddd55555555cccc.....................",
    "......................dd55ccc55d44ddd46eee644ddddddddddd555ddd555555cccccc......................",
    "........................555cccd4444dddbee6664dddddddddd5555555555555cccc........................",
    "..........................5ccc544444dd46e66ddddddd446d5555555555555ccc..........................",
    "............................ccc444d55dd466bddddddd664d555555555555cc............................",
    "..............................c545555ddd6e64dddddd666d5555cc5555cc..............................",
    ".................................5555ddd4666dddddd44dd555ccc55c.................................",
    "....................................5d5dd46664dddddd55555ccc....................................",
    ".........................................d6ee6ddddd5555.........................................",
)
